management.address
endpoints.shutdown.enabled
shell.ssh.enabled
shell.ssh.port
shell.auth
security.require_ssl

spring.datasource.url=jdbc:h2:mem:saesubamdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

server.port=8080
logging.file.name=app.log

# Spring Mail (SMTP) Configuration for sending Real Emails to Inbox (e.g. Gmail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=vigneshn051995@gmail.com
spring.mail.password=inszhpkobjgntzbu
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
# saesubam.matrimony@gmail.com
